from tkinter import *
root=Tk()
root.geometry("600x500")
f1=Frame(root, bg="Grey",  borderwidth=4, relief=SOLID)
f1.pack(side=LEFT, fill=Y)
f2=Frame(root, bg="Light Grey", height=500, width=850)
f2.pack(fill=X)
f3=Frame(root, bg="Light Yellow", height=300, width=850, borderwidth=5, relief=SUNKEN)
f3.pack(side=BOTTOM, fill=X)
l1=Label(f1,text="EXPLORER",  bg="Light Blue", fg="Green", font="calibri 15 bold")
l1.pack()
l2=Label(f1,text="TIMELINE", padx=80, pady=10, bg="Light Blue", fg="Green", font="calibri 15 bold")
l2.pack(side=BOTTOM)
l3=Label(f2,text="Just write the piece of code you want to run.........", font="arial 10")
l3.pack(side=LEFT,fill=X)
# l4=Label(f3,text="PROBLEMS", font="calibri 15 bold")
# l4.pack()
root.mainloop()